[project]
name = "research-mcp"
version = "0.1.0"
description = "Deep research MCP server."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.13.0",
    "python-dotenv>=1.1.1",
    "strands-agents-tools>=0.2.3",
    "strands-agents[ollama]>=1.4.0",
]

[dependency-groups]
dev = [
    "black>=25.1.0",
    "mypy>=1.17.1",
]
